### ISSUE TITLE
Versioning of property changes

### ISSUE THREAD

**Issue by amervitz** [Microsoft/CDM#10]
Are property level changes allowed with respect to ensuring backwards and forwards compatibility? There are multiple types of changes that could break the backwards compatibility requirement, for example:

- changing the `maxLength` on a string attribute, by increasing from 250 to 300 could break an application on an older version of the schema expecting a maxLength of 250 and receiving 300 from an application running on a newer schema that accepts a maxLength of 300
    ````json
    {
        "name": "address1_line1",
        "dataType": "String",
        "displayName": "Address 1: Street 1",
        "description": "Type the first line of the primary address.",
        "semanticDomain": {
            "semanticType": "Location.Address.Street",
            "maxLength": 250,
            "inherited": true
        }
    }
- adding a new value to a `constrainedList` could break an old application/schema not expecting an new schema with an additional value of 5/Secondary
    ```json
    {
        "name": "address1_addresstypecode",
        "dataType": "String",
        "displayName": "Address 1: Address Type",
        "description": "Select the primary address type.",
        "semanticDomain": {
            "semanticType": "Measurement.OptionCode",
            "inherited": true,
            "constrainedList": {
                "name": "account_address1_addresstypecode",
                "displayName": "Address 1: Address Type",
                "description": "Type of address for address 1, such as billing, shipping, or primary address.",
                "items": [
                    {
                        "value": 1,
                        "displayName": "Bill To"
                    },
                    {
                        "value": 2,
                        "displayName": "Ship To"
                    },
                    {
                        "value": 3,
                        "displayName": "Primary"
                    },
                    {
                        "value": 4,
                        "displayName": "Other"
                    }
                ]
            }
        }
    }

**Comment by DavidRMicrosoft** [comment]
You're right. The types of changes you mention could cause back compat issues. 

Any change has a non-zero probability of breaking something that depends on the condition that changed, but some changes have a higher probability than others. We'll try to balance requirements to support enhanced functionality and stability with the goal of _minimizing_ breaking changes. 

Let's take the example of increasing an attribute's maxLength property. We may have a data loss condition during ingestion from an external source that truncates contents because the string length on the source system was longer, or even worse, that causes a failure in the ingestion process that suppresses the entire row. If we believe increasing the size is well-justified because many customers would be likely to experience similar failures, then we will make the change at the expense of a relatively lower probability of breaking existing applications. 

All publishers need to minimize the negative impact of changes to existing specs. We give some examples of changes that aren't allowed because the probability of back compat problems is predictably high (such as changing an attribute property to mandatory from optional), but this cannot preclude all changes.

**Comment by amervitz** [comment]
Rules for how applications should behave when receiving inputs that fall outside their known schema would help with the compatibility goal. For example, that a receiving application should truncate values that exceed the maxLength, and ignore values outside the allowed range or schema definition. Is this within the realm the CDM specification effort?

**Comment by DavidRMicrosoft** [comment]
Prescriptive guidance for application behavior is outside of the scope of the CDM schema specification.

**Comment by amervitz** [comment]
Who will provide this prescriptive guidance? This is fundamental to satisfying backwards and forwards compatibility. Model-driven apps and systems built upon CDM will need an agreed upon set of conventions/behavior in how to handle data input and exchange. I'm sure PowerApps/Dynamics 365 and other common data service implementations inside Microsoft will follow the same conventions, but how will other implementations know what rules to follow to be compatible?

**Comment by DavidRMicrosoft** [comment]
The standard schema published here is a first but significant step toward supporting interoperability across systems, provided those systems represent their data in a way that conforms to the archetypal schema. It does not and cannot guarantee interoperability, and it will change over time in response to legitimate needs.

The "last mile" of application compatibility and interoperability is the responsibility of the applications themselves, as implemented by their respective developers. This includes low-level considerations such as string field lengths, internal representations of dates and date/times, precision/scale of numeric data, option set/picklist domain elements, etc., and extends to structural considerations such as alternate key shapes and specialized entity schema. This responsibility also includes the change management protocols necessary to uptake new versions of schema.

We deliberately chose to base CDM on the "looser" standards characteristic of CRM or xRM schemas, rather than the more restrictive aspects typical of ERP systems. No single schema specification will comprehensively mediate the operational differences between CRM and ERP applications, for example. We're sincerely appreciative of constructive feedback that will help us do better.
