### ISSUE TITLE
Resolved entities not able to mount in different namespace

### ISSUE THREAD

**Issue by Akkilz** [microsoft/CDM#139]
I have kept foundation in cdm namesapce, abstract manifest in absAdl namespace and I am trying to generate resolved manifest, entities in resAdl namesapce.

Resolved entities being created under absAdl instead of resAdl.
Config,resolved.manifest.cdm.json and model.json are created under resAdl.

Refered example c# : 4-read-local-save-adls

Code : 
 ```
const string foundationJsonPath = "cdm:/foundations.cdm.json";
                const string manifestPathAbs = "absAdls:/abstractDigitalTwin.manifest.cdm.json";
                var cdmCorpus = new CdmCorpusDefinition();
                var adlHost = "{adl gen2 host name}.dfs.core.windows.net";
                var adlAccessKey = "{adlGen2 access key}";
                var adlPublicStandardsPath = "/cdm-foundation/public-standards"; // kept public std cdm files
                var adlAbstractPath = "/cdm-abstract/CDM-Simple"; // abstract manifest
                var adlResolvedPath = "/cdm-resolved/cdm-resolved";

                cdmCorpus.Storage.Mount("cdm", new ADLSAdapter(adlHost, adlPublicStandardsPath, adlAccessKey));
                cdmCorpus.Storage.Mount("absAdls", new ADLSAdapter(adlHost, adlAbstractPath, adlAccessKey));
                cdmCorpus.Storage.Mount("resAdls", new ADLSAdapter(adlHost, adlResolvedPath, adlAccessKey));

//Read abstract manifest 
                CdmManifestDefinition manifest = await cdmCorpus.FetchObjectAsync<CdmManifestDefinition>(manifestPathAbs);

// Generated resolved manifest
                var manifestResolved = await manifest.CreateResolvedManifestAsync("digitalTwin", null);
                manifestResolved.Imports.Add(foundationJsonPath);


                CdmFolderDefinition adlsFolder = cdmCorpus.Storage.FetchRootFolder("resAdls");
                adlsFolder.Documents.Add(manifestResolved);

// resolved entities created in **absAdls** namespace.
                var resolvedStatus = await manifestResolved.SaveAsAsync($"{manifestResolved.ManifestName}.manifest.cdm.json", true);

//model is created fine bcz entities are inside.
                await manifestResolved.SaveAsAsync("model.json", true);
            }
```

**Comment by Akkilz** [comment]
[CDM-abstract -simple.zip](https://github.com/microsoft/CDM/files/4342674/CDM-abstract.-simple.zip)

sample abstract manifest being used in this sample,

Foundation version : 1.0.0

**Comment by mfriscia7** [comment]
Moving the resolved manifest to the adls namespace in this way will not currently move the linked files (like the entity files that are listed in the manifest). Instead of doing this, I would recommend changing the way you call CreateResolvedManifestAsync in this way:

`CreateResolvedManifestAsync('adls:/digitalTwin', 'adls:/{n}.cdm.json'')`

The first parameter will automatically add the resolved manifest to the adls adapter. The second parameter provides a rename format for the entities that are created ([see the documentation here](https://docs.microsoft.com/en-us/common-data-model/0.9om/api-reference/cdm/manifest#methods)). By adding the namespace to this rename format, each entity will be added to the adls namespace.

With this solution you will not need to manually add the manifest to folder and you can just call 'SaveAsAsync' on the resolved manifest

**Comment by Akkilz** [comment]
Thanks for the help and its working as expected.
