### ISSUE TITLE
Python entity.attributes of type CdmAttributeGroupReference

### ISSUE THREAD

**Issue by momohuri** [microsoft/CDM#152]
Hi, 
I have been trying to replicate the sample 1 "Read Manifest" in python. 
I am able to fetch the manifest and list the entities but when I want to list the attributes of a specific entity I get attributes that are instance of the class CdmAttributeGroupReference, which does not contains info like name and data type. 
Is there some extra steps needed in python to get the attributes ?

c# code : 
```
        static void ListAttributes(CdmEntityDefinition entity)
        {
            Console.WriteLine($"\nList of all attributes for the entity {entity.EntityName}:");

            // This way of getting the attributes only works well for 'resolved' entities that have been flattened out.
            // An abstract entity can be resolved by calling createResolvedEntity on it.
            foreach (CdmTypeAttributeDefinition attribute in entity.Attributes)
            {
                // Attribute's name.
                PrintProperty("Name", attribute.Name);
                // Attribute's data format.
                PrintProperty("DataFormat", attribute.DataFormat.ToString());
                // And all the traits of this attribute.
                Console.WriteLine("AppliedTraits:");
                foreach (var trait in attribute.AppliedTraits)
                {
                    PrintTrait(trait);
                }
                Console.WriteLine();
            }
        }
```
python code: 

```
def ListAttributes(entity):
    print("List of all attributes for the entity {}:".format(entity.entity_name))
    for attribute in entity.attributes:
        if "name" in attribute:
            print("Name : {}".format(attribute.name)) # <--- this is breaking
            print("DataFromat: {}".format(attribute.data_format))
```

**Comment by mfriscia7** [comment]
Hello, as you can see from the comment in the C# code snippet, looping through attributes this way only works well for 'resolved' entities. In the python code are you pointing at the resolved version of the entities? Because of the way the storage adapters are setup, the C# sample is pointing at the resolved entities which can be found [here](https://github.com/microsoft/CDM/tree/master/samples/1-read-manifest).

**Comment by momohuri** [comment]
Hi, 
I have setup a Local Storage pointing to the "[/schemaDocuments](https://github.com/microsoft/CDM/tree/master/schemaDocuments)" folder.
Then I am using the electronicMedicalRecordsAccelerator manifest. 
What you are saying seems to imply that then I am not fetching a resolved entity, what would be the type of entity that I am fetching ? How could I get the attributes of those kind of entities? or how could I get a 'resolved' entity.

The problem that I am trying to solve is: how in python can I get all the attributes of an entity (like account) for the electronicMedicalRecordsAccelerator manifest.

My code so far: https://gist.github.com/momohuri/800c508c4b3180e41076e56766b55049

Thanks for your answer.

**Comment by mfriscia7** [comment]
This [document ](https://docs.microsoft.com/en-us/common-data-model/creating-schemas)describes the difference between logical and physical entities:

> Physical - The entities that exist in your data, often as tables in a database. This  means that the entity schemas that you'll create for your physical  entities will represent your data in the Common Data Model format. For  instance, the attributes described in a Common Data Model entity schema  are derived from the fields (or columns) of the corresponding physical  entity.
--
Logical - Purely logical entities, on the other hand, aren't trying to  describe an existing physical entity. Instead, they're used to  encapsulate commonly used attributes (fields that appear across your  physical entities) into meaningful groups. Logical entities allow us to  define common attributes once and reuse these definitions, rather than  re-defining the same attribute every time it's used in an entity  definition. The entity schemas for logical entities represent the  logical entity definitions in the Common Data Model format, rather than actual data.


The entities that you are using are logical entities. The CDM SDK can be used to "resolve" the logical entities into physical entities (or what I called resolved entities).

The sample you are trying to replicate is using resolved entities in [this folder](https://github.com/microsoft/CDM/tree/master/samples/1-read-manifest) which are the physical (or resolved) versions of a few of the logical entities you are seeing in the /schemaDocuments folder.

Also, you don't have to use the physical entities that the sample uses. You can generate physical entities from logical entities using some of the SDK's APIs (CdmEntityDefinition.CreateResolvedEntityAsync for a single entity or CdmManifestDefinition.CreateResolvedManifestAsync to resolve all entities listed in a manifest). [We also have a sample that shows how to resolve a manifest and save the physical versions of the entities in a manifest](https://github.com/microsoft/CDM/tree/master/samples/6-create-net-new-entities).

I hope that helps!
