### ISSUE TITLE
Industry accelerators and Entities Navigator

### ISSUE THREAD

**Issue by jjcp** [microsoft/CDM#155]
I would like to understand the difference between the healthcare industry accelerator defined in the CDM and the one defined in the [Industry-Accelerator-Health]( https://github.com/microsoft/Industry-Accelerator-Health) repo which seems to be significantly larger than what's available here.

Also, the [Industry-Accelerator-Health]( https://github.com/microsoft/Industry-Accelerator-Health) schemas are defined using XML instead of JSON files which prevent me from pointing the CDM Entity Navigator at them, how do you go about using those XML files? is there a converter somewhere?

Any help is appreciated.

**Comment by jinichu** [comment]
The schemas defined in the CDM repo and the Industry-Accelerator-Health repo are meant to be the same. They are currently out of sync however, with the Industry-Accelerator-Health repo having the latest. We are in the process of updating and publishing these schemas so that the CDM repo is in sync. Once that happens, you will be able to see the latest health care industry accelerator schemas on the CDM Entity Navigator too.

**Comment by jjcp** [comment]
Thank you for the information! Any idea on when the update might happen?

**Comment by jinichu** [comment]
The update should happen soon -- there are some changes that need to come in that we are awaiting, which shouldn't take too long to resolve. I can update this thread once the schemas are published.

**Comment by jjcp** [comment]
Great, thanks a lot!

**Comment by jinichu** [comment]
We have published the new schemas. You can find it here: https://github.com/microsoft/CDM/tree/master/schemaDocuments
