### ISSUE TITLE
model json vs manifest 

### ISSUE THREAD

**Issue by mithun1979** [microsoft/CDM#156]
Hi, 
Could you please help with a clarification.
I have been successfully using Power BI dataflows with CDM metatdata stored in 
model.json. Are there any specific advantages of using manifests for metadata storage instead.

Thanks and Regards
Saurav Chakraborty

**Comment by llawwaii** [comment]
Hi Saurav,

I recommend you to visit [Common Data Model Page](https://docs.microsoft.com/en-us/common-data-model/#why-use-common-data-model) for more details first. If you have more questions, please let us know.

Thanks,
Phoenix

**Comment by mithun1979** [comment]
Thanks for the response. I went thru the same and have understood that the main driver for this is to build a common data format to facilitate interoperability between data producers and data consumers. 

I have been using model.json to manage metadata for CDM, for the past few months. I also noticed that there is a new option of using manifests for managing metadata and wanted to understand the driving factors for this new metadata management option.

 Would you be able to help with  high level direction on  choosing between model.json over manifest to manage the CDM metadata or vice versa. 

Thanks and Regards
Saurav Chakraborty

**Comment by olegovanesyan** [comment]
Hi Saurav. Manifest oriented metadata is an evolution of CDM metadata format. It is richer and allows for scenarios previously unavailable in model.json oriented metadata, for example, instead of having specific URL for every new data partition as it is added to the folder, one can specify search pattern in the manifest. We are encouraging adoption of the manifest based approach, however, we've added support for model.json to CDM SDK.

For documentation and details pls visit:

https://docs.microsoft.com/en-us/common-data-model/cdm-manifest 
https://docs.microsoft.com/en-us/common-data-model/sdk/manifest

For specific examples using CDM SDK - https://github.com/microsoft/CDM/tree/master/samples

**Comment by mithun1979** [comment]
Thanks for the response.

Regards
Saurav Chakraborty

**Comment by clintgrove** [comment]
We are creating our CDM using the manifest.cdm.json instead of a model.json, however this causes and issue because Power BI dataflows only accept a model.json file. So Power BI needs to shape up and allow us to use the manifest.cdm.json
