### ISSUE TITLE
partition-data.csv get generated automatically or how we define those  

### ISSUE THREAD

**Issue by rahuljim** [microsoft/CDM#162]
hi i have following queries on below 
https://github.com/microsoft/CDM/tree/master/samples/6-create-net-new-entities
 Does partition-data.csv get generated automatically or their are any procedure for their creation  
 how can we mouth Manifest , Partition data to the ADLS gen 2 ?

**Comment by victor-gutemberg** [comment]
Hello,

this sample currently doesn't generate the CSV file.
You can have a look at the `2-create-manifest` sample since it includes a small code snipped to create a CSV header containing the attribute names and save that to your local disk.

In short all you need to do is put the code below after [this line](https://github.com/microsoft/CDM/blob/85511bde07751b513b5aa36d8ec80781f6bf4ce7/samples/6-create-net-new-entities/code-cs/create-net-new-entities/Program.cs#L183).

```
// Make a fake file with nothing but header for columns
string header = "";
foreach(CdmTypeAttributeDefinition att in entDef.Attributes)
{
    if (header != "")
        header += ",";
    header += att.Name;
}

await cdmCorpus.Storage.FetchAdapter("adls").WriteAsync("/path/data-partition.csv", header);
```


Just remember that you also need to uncomment the part of the code where you mount the "adls" adapter.

**Comment by rahuljim** [comment]
Thanks
