### ISSUE TITLE
CDM File System does not necessary a Windows File System

### ISSUE THREAD

**Issue by biztalk** [microsoft/CDM#165]
this CDM library assumed that the file system will be Windows file system. You will find in many places "upper case" & "lower case" path names are intermixed. You will also find "\\" and "/" are intermixed. You will also find volume separator 'C:' is assumed. Try to build and test this library in the Microsoft Visual Studio Codespace to see if you can pass all test cases.

**Comment by dingbx** [comment]
Hi,

Thanks for reporting the issue.
Can you provide more details about which language of CDM SDK you are using and where you see these errors? It would be helpful for us to repro and fix it.

Thanks,
Yijing

**Comment by biztalk** [comment]
[attached](https://github.com/biztalk/cdm-comments/blob/master/test%20cases%20%C2%B7%20changes.mht) please see some examples of issues when using Linux fs or other non-windows file systems.

**Comment by dingbx** [comment]
Thanks for the mht file. We will investigate this issue further this week.

**Comment by jinichu** [comment]
Hi there. 

We currently do not support running the tests on a non-Windows file system, as we do not yet have a Linux machine set up as part of our environment. If you would like, you can send a PR to add Linux support in the tests. I took a look at the mht file you have attached and noticed that one of the tests (TestFetchingAndSavingDocumentsWithCaseInsensitiveCheck) was changed so that the file names/extensions are all lower-case. However, in this test, the capitalization should be kept because we _want_ to be checking that the CDM library is case insensitive to file names/extensions as this is supported in Windows. For that test, you could add a check to just skip it if running on Linux.

**Comment by biztalk** [comment]
Isn't CDM going to be used with ADLSg2? If I understand it correctly, the ADLSg2 file system (including HDFS) will be a Linux FS and the filenames are case-sensitive ? You don't need to have Linux setup to test this, you can just load it with visual studio codespace VM, it is all Linux only. Further, Windows 10 do support case-sensitive too (https://www.howtogeek.com/354220/how-to-enable-case-sensitive-folders-on-windows-10/)

**Comment by SukanyaSrinivasan** [comment]
Hi,
Thank you for your feedback. At this time we don't plan to support Linux FS.
