### ISSUE TITLE
missing "extendsTrait" references in primitives.cdm.json

### ISSUE THREAD

**Issue by WildDylanX** [microsoft/CDM#176]
Hello,
This is my first time contributing here, so I apologize if I am misunderstanding the purpose.  I have been spending some time today trying to parse my way through the [foundations.cdm.json](https://github.com/microsoft/CDM/blob/master/schemaDocuments/primitives.cdm.json) file to better understand the hierarchies of traits, dataTypes, entities, and purposes.  Although I found that almost all traits seemed to follow a strict hierarchy of extending traits all the way back to **is**, I did notice 3 exceptions:
**is.linkedEntity** didn't seem to contain an "extendsTrait" reference, though I thought based upon its name that it should extend back to **is**
**is.linkedEntity.array** also didn't contain an "extendsTrait" but I thought similarly that it should extend **is.linkedEntity**, and
**is.linkedEntity.array.count** didn't have an "extendsTrait" either, though I thought it might be an extension of **is.linkedEntity.array**

I'm sorry to raise alarm if this was intentional, but I would greatly appreciate an explanation (for my own understanding) why these 3 traits seem to be orphaned.

**Comment by JeffBern** [comment]
Be sure to check out the docs on CDM here https://docs.microsoft.com/en-us/common-data-model/sdk/overview before grinding too much on some things.
Specifically on the three traits you mentioned the answer is a mix between "it’s complicated" and "probably a mistake" The complicated answer is that these traits are used internally by CDM to mark 'artifact' attributes that get generated by resolving entities and so keeping the definition simple was probably on the mind of the person who created them, or that person forgot. Also of note, that person was me.
As a side note, an 'artifact' attribute is one that doesn't really exist in the logical model but gets spit out under some circumstances. A foreign key is a good example, in our model all of the attributes from a related entity can be replaced by a foreign key, so that key gets added with the note that it is a linked entity identifier.

There is no rule that traits need to inherit from other traits, we have just been doing it to keep things organized. However, my thinking on trait inheritance has 'matured' over time. At first I was using it in a kind of sloppy way as both a 'same kind of thing' indicator and as a kind of grouping and classification mechanism but now I want to use is strictly as a sub-class indicator. (same kind of thing, but more specialized).

The root traits were meant to be the kind of 'action' being expressed so you see the things like "is", "does", "means", "has".  Beyond that, I made some mistakes and used inheritance to organize and group traits in a way that violates the 'is a' relationship. There are some traits that ARE NOT the same kind of thing as their superclass trait, but they come from the same domain of ideas and so ... Now, the example you mention, is.linkedEntity.array and is.linkedEntity.array.count, those are two different but related ideas. is.linkedEntity.array means there can be many instances of a linked entity wereas is.linkedEntity.array.count indicates a column that tells you the number of instances of the linked entity that should show up in a row of data (when denormalized) I should not have an inheritance relationship there. 

The “right” way to use trait inheritance is to allow for polymorphic use of the base trait. For example, means.measurement.physicalDimension, means.measurement.physicalDimension.time and means.measurement.physicalDimension.voltage. The inheritance works here because one may need to find all traits that are measuring physical things and then for each trait, read the argument that tells you the name of the dimension being measured.

Anyway, I am getting a little deep here.
-jeff

**Comment by WildDylanX** [comment]
Wow! I must say I'm impressed (and even a little intimidated) to have gotten such a detailed response so quickly - especially from one of the lead devs on the CDM project!
Thank-you very much for the link to the docs on the Common Data Model; I've done a number of Google searches and have found a few resources on the Microsoft site already, but I don't remember coming across this one before.  Unfortunately, I've found it quite challenging to find detailed documentation (besides analyzing the code itself on Github) to learn about generating CDM schemas, building off of the work that already exists in Github.  I actually built a process in Power Automate to generate the foundations.cdm.json files for a list of entities and attributes (with their relationships) that our organization is trying to model in CDM using the [CDM Schema reference](https://docs.microsoft.com/en-us/common-data-model/creating-schemas) as a guide. It seems to work okay on the initial tests we've done importing them through ADF, though the Architecture Owner on the project I'm leading tells me he's run into a few snags figuring out how to generate manifest files that contain all of our entities together and he's been struggling to get quick responses from our MS rep (though, in fairness our rep is on summer vacay this week).
All this is to say, I sincerely appreciate your taking the time to "go deep" on your response and helping to educate me in the meantime.  Today, as I was building my own comprehension of the primitives file, I created the attached "tree view" of the traits, dataTypes, etc to help me picture what inherited from what.  Since it's based on your work, I'm happy to share  :) 
I was actually working on a programmatic way to generate such a view; I know about the [CDM Entity Navigator](https://microsoft.github.io/CDM/SchemaViz.html), but unfortunately I couldn't figure out how to explore just the traits and dataTypes to figure out where we we would need to build our own schema definitions starting from.  Our MS rep also shared a [new tool](https://industrydataworkbench.azurewebsites.net/) that I understand is supposed to be available soon; however, when I log into it with my work account, it says I'm unauthorized. :(
One good point I took away from your explanation is that it is possible (perhaps even desirable) to not have all traits inheriting from other traits.  I expect I've still got a number of valuable lessons to learn here! I think I know what you are talking about with some traits not matching their superclass trait (at first I was puzzled by the is.identifiedBy, is.named, is.ordered, and is.locatable which all are trait extensions of does.elevateAttribute, but since I was able to trace the lineage back through the "extendsTrait", I just assumed that there was a logical reason why these needed to go here).

[CDM primitives decomposition.pdf](https://github.com/microsoft/CDM/files/5144858/CDM.primitives.decomposition.pdf)

Best regards,
Dylan
