### ISSUE TITLE
CDM & OWL/RDF 

### ISSUE THREAD

**Issue by MSabanfi** [microsoft/CDM#279]
Does CDM support open/standard language like OWL/RDF for the semantic layer definition? 
Does CDM can import external semantic layer defined with OWL/RDF?
How CDM can be integrated with enforce policies rules or provide search capabilities to consumers / producers?

**Comment by matgos** [comment]
Hi MSabanfi,

Thanks for the questions.  OWL\RDF was evaluated during CDM design and although many of the principals of semantics apply, CDM did not adopt OWL\RDF, the primary reason being that CDM had a specific need (at the time) to integrate specific Microsoft business applications and create a standard entity definition layer that was descriptive and extensible, and ultimately built upon by our ecosystem.

Moving forward a few years.... CDM evolved to meet customer demand and was quickly adopted by customers and partners to create their own models based on the standardized shapes (entities) offered by the CDM metadata system using a language or framework that could integrate with Microsoft ecosystem application and services.   Although CDM doesn't have an import or conversion tool for OWL\RDF-to-CDM (and vice-versa), the CDM SDK (https://github.com/microsoft/CDM/tree/master/objectModel) can be used to build a solution for this purpose.

To your third question, 'Yes', this is the 'sweet spot' for CDM - having the ability to describe\annotate data with semantics - we call these semantic hints 'traits' - that can be used by applications and services to identify data based on its meaning (the traits) rather than depending on column headers, data types or properties (width, language, kanatype, collation, etc.) alone. 
The CDM SDK can be leveraged to create a search\browse capability to serve policy-based applications.

Thanks again for the great questions.

All the best,

Matt.

**Comment by pietercolpaert** [comment]
Think it would make sense though that microsoft puts forward global IRIs described within RDF to make sure people using it within RDF all use the same identifiers for the same concepts. As microsoft participates in Schema.org, it could create these there? @danbri

**Comment by danbri** [comment]
I'd suggest Wikidata might be better home for large numbers of entity identifiers

But If the CDM folks are interested to collaborate around Schema.org - always happy to chat!
