### ISSUE TITLE
Extract superclass from CDM Hierarchy

### ISSUE THREAD

**Issue by Green-Cherub** [microsoft/CDM#295]
Hi, I'm trying to understand CDM. I need to create a python function that takes in a word ("account"), runs it through the CDM schema and returns a superclass (financial Services) of that input word.

E.g. 

def get_superclass(word='account'):
    superclass = #Get superclass of 'account', which is 'financial Services' from CDM schema 
    return superclass

I'll like to know how to work with CDM to achieve this.
Thank you.

**Comment by mfriscia7** [comment]
Hello, the CDM sdk will not be able to help you achieve that. You will need to take the schema files (mainly the manifest files) and create the functionality yourself.

In order to do what you are looking for, you would need to create a mapping of all of the manifests and the entities that are contained in them. Manifest objects point to other manifests called "submanifests" and mean you will have a hierarchy of manifests and a path to follow to find the "superclass". Then when you are looking for "account" you would look through that manifest hierarchy until you find the superclass that you are looking for.

**Comment by Green-Cherub** [comment]
Thank you. Is there a document that has a list of the manifestName and the related entityNames or do I need to go through all the files to pick them out?

**Comment by dingbx** [comment]
We have a documentation on entity references, https://docs.microsoft.com/en-us/common-data-model/schema/core/overview, is it what you are looking for?

**Comment by Venkata1920** [comment]
Hi @Green-Cherub, are you looking for additional information? If so, could you please respond to the previous query? If you have all the information you'd requested, then please feel free to close the issue.
