### ISSUE TITLE
Obsolescence and "Internal Use only"

### ISSUE THREAD

**Issue by joern-schlingensiepen** [microsoft/CDM#316]
Today we have 48 obsolete API in the SKD that do not have a hint to an alternative and a lot of obsolete API declared as "Internal Use Only". 

Can we have a version of the SDK consolidating this issues.

**Comment by victor-gutemberg** [comment]
hello @joern-schlingensiepen,

The CDM SDK has evolved over the years and as part of this process we've added new APIs that are easier to use, while marking those that could cause confusion to our customers as deprecated. 
As you mentioned, some of these deprecated APIs are used internally by our code so we still kept them.

We also didn't completely remove the deprecated APIs because that could cause problems for customers when updating to a new version.

Is there a specific scenario where you see the use of an API that is marked as deprecated?

**Comment by joern-schlingensiepen** [comment]
Dear Victor,

I like the idea of using tags like 'deprecation' to ensure a development of tools. It would be helpful to give users an advice which alternatives one has to use. In most cases this is done in CDM SDK, but for 48 APIs I do not see this.

My current issue is 'namespace'. We can mount different LocalStores for different Namespaces (which implies a relation between a namespace and a document). From my (current) understanding namespaces can help to organize different types in logical packages, e.g. to avoid interference in naming, etc.

But since the API for namespaces in Documents is 'deprecated' I am sure that I misunderstood this concept. My approach was, asking the Owner (which is a document) for the namespace. An alternative is using the namespace of a folder. But I do not see any api for getting a folder of a CdmObject (e.g. CDMEntityDefinition).

Could you give me an advice, where to find information about organizing namespaces in the docs?

Best Regards

Jörn

**Comment by mfriscia7** [comment]
The namespace for a document is determined by the adapter that it originates from. I believe that it is marked as deprecated because it should not be modified by the user and that should only be used internally to determine paths for objects inside of the document. What are you trying to accomplish with the namespace? Are you just trying to keep track of what adapter each document comes from?

**Comment by joern-schlingensiepen** [comment]
Hi, 

we try to express data models from industrial context in CDM, so it would be nice to map their namespace structure to a namespace structure in CDM.

So, for me it is not a question, where does a ___Definition comes from but where to place it on creation.

BR

Jörn

**Comment by mfriscia7** [comment]
Namespace for CDM has to do more with the location where the definitions exist. It sounds to me like you should use CdmFolderDefinitions and CdmManifestDefintinitions to replicate the namespace structure that you have. Maybe for each namespace you have, you can create a new manifest (with the name of that namespace) and that manifest would contain all of the entities that you expect in that namespace.

**Comment by joern-schlingensiepen** [comment]
Ok, as I expected I got a wrong understanding here. Thanks for your help!

Btw: From my point of view the handling of manifest and files is way to complicated in the current SDK, there should be some convenience functions. With the current way developers will not love to work with it.

BR

Jörn
