### ISSUE TITLE
Default decimal precision and scale

### ISSUE THREAD

**Issue by Willem-J-an** [microsoft/CDM#317]
If decimal precision and scale are omitted as traits from the metadata, as is the case in all decimals at 1-read-manifest sample, what would be the default precision and scale according to CDM format?

**Comment by Willem-J-an** [comment]
Hi @Venkata1920, thanks for getting back to me.
I suppose all the information is as it is defined in source, but we're not reading the source, we're reading CDM. To allow for proper integrations, the information is needed in CDM too I think. Is including precision and scale mandatory? Or at least is it unlikely to be missing when using a standard integration like Synapse Link for Dataverse?

**Comment by Venkata1920** [comment]
Hi @Willem-J-an, including the scale and precision is not mandatory but recommended. As for the query about them being present or missing when using standard integration like Synapse Link, it is unlikely but not impossible since the schema definition / validation is owned by the Product area / Solution owners. Hope this helps!
