### ISSUE TITLE
question

### ISSUE THREAD

**Issue by duncancockburn** [Microsoft/CDM#48]
Every business has unique data and operations. although it would be possible to standardise data from some businesses in similar industries, how does the possibility of a company with various business operations impact the ability to create a CDM?

**Comment by JeffBern** [comment]
Thanks for asking such a difficult question! I will do my best to answer it. 

As background: The goal of sharing these schemas openly is to help start a kind of economic feedback cycle where the data produced by one application can be used "more easily" by new applications to make something valuable. The value from these new applications would then create an incentive for other new applications to adopt and write data into the same schemas. rinse and repeat. 
We could be "schema first" and try to create the ideal “best” versions of entities and ideas, but those are hard to get right and it takes a big leap of faith for the very first application to adopt. Instead we went "data first" and describe in a generic way the existing data that customers of Dynamics and other application will already have. The downside being that some entities and ideas are a bit "warty" because they have evolved over time.

So to your question, we will continue to add industry specific schemas and we will push for them to be consistent and shared when we can. Of course we can't describe every industry so how will big complex businesses benefit from the CDM? They will benefit because we have also made a ‘language’ of sorts that can express schema in a rich way with an extensible system for attaching types and semantic ideas. As our tools and applications and external tools and applications begin to understand and react to these schema ‘traits’ (the word we used), then even completely new schemas from a customer’s industry could benefit from the tooling or be made to interact with the published schemas. 
I know that was abstract, so I will give a concrete example. Imagine that a new set of data for oil wells contains these attributes (ID, name of the well, region of the country, zipcode, latitude, longitude)  the CDM has (or soon will have) well defined semantic traits for concepts like “primary key”, “instance name”, “description”, “geography” and “hierarchy”. If the oil well schema is ascribed these traits: (ID is primaryKey, nameOfWell is instanceName and description, regionOfCOuntry is geography.region and hierarchyUnder(), zipCode is geography.zip and hierarchyUnder(“region”), etc.) then I can imagine a trait aware application that can show wells on a map. I can imagine it showing a hierarchy of wells per zipcode per region. I can imagine it using the name of the well as the label or tool tip.
See how that can work?
-jeff
