### ISSUE TITLE
GoalMetric doesn't have a value

### ISSUE THREAD

**Issue by cwhd** [Microsoft/CDM#54]
I was considering using the CDM for some metric analysis and when I look through it I think that it makes sense to have the Goal entity which represents something a team or user is working toward, and the GoalMetric which represents the metrics that are used to track towards the goal. However shouldn't the GoalMetric have a field for value or current value? For example if you take the example of a sales team that has a goal of a certain number of conversions of some type you could set up the goal, then the GoalMetric would be "conversions" which would hold some value, but I don't see anywhere in that entity where the current number of conversions would be. If that make sense I'm happy to submit a PR, let me know if I'm missing something. Thanks!

**Comment by DavidRMicrosoft** [comment]
The GoalMetric entity describes _types_ of metrics, not the metrics themselves, which is why it doesn't contain an attribute corresponding to the metric value. Each tuple in the Goal entity represents an instance of a GoalMetric and contains both target and actual values. The Goal entity uses rollup queries in Dynamics 365 Customer Engagement (CE) to derive actuals; without the rollup logic, it would be difficult to adapt the Goal-related entities for use in a custom scenario.

For more information on using Goals in Dynamics 365, see the section "Goal Management" on this [page](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/sales-enterprise/admin-guide).

Rollup fields are described in more detail on this [page](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/customize/define-rollup-fields).

**Comment by cwhd** [comment]
Ok, that makes sense. Thanks.
