### ISSUE TITLE
Specification Document

### ISSUE THREAD

**Issue by shaggygi** [microsoft/CDM#73]
Understanding the data model is extensible, but is there an official document that describes the modeling language?  It would be nice to understand some of the following...

- Is the model purely based on JSON or can it be other formats (XML, CSV, etc.)
- Primitive data types
- Defined data types.  For example, what is a LookupType or MemoType and what elements are they built upon?
- Model properties link to other models
- How to structure your own model (new and one extending a defined model)
- How to create your own CDM Folder and related contents to include.
- What data elements are required, how do you show that are required? 
- What data elements are nullable, how do you show they can be missing or their value can be null? 
- Explanation of trait information.  is.dataFormat, is.dataFormat.big, means.content.text.HTML, means.identity.entityId, etc.

**Comment by JeffBern** [comment]
We are in the middle of crafting the kind of documentation you describe, and you questions are actually good feedback on the kind of topics that such documentation should cover.
I can give some short answers here. Note that there are two object models for CDM right now (one for model.json files and one for the standard entities) but we are quite close to putting out one unified model for both. I'm not sure which model you mean, so I will do my best:
1. the json documents are the "persisted form" of an object model. We are actually working on some alternate persistence forms, so yes it is possible for sure. I'm not sure what a csv version would look like since there is some deep structure needed to express the ideas though.
2. for model.json, the primitive types are in the docs under samples/cdm-folder. for the standards there is a file called primitives.cdm.json that may help.
3. most of the ideas in the standard entities are built up in the 4 files primitives, meanings, foundations and wellKnownCDSAttributeGroups.cdm.json
4.
5. there are examples in the standards of entities that extend other entities, account.cdm.json for example.
the samples/cdm-folders docs explain how to make a folder
for the standard entities, there are traits that explain if an attribute is "nullable" and there is a trait that captures the "requirement level" of the values from the cds metadata.
regards,
jeff

**Comment by shaggygi** [comment]
@JeffBern 

> putting out one unified model for both

Understanding things are still in development, does this mean the models will completely change?  Or is it safe to say that if one begins studying the formats it will be carried over into the unified model?  Thx

**Comment by shaggygi** [comment]
If one of the future goals is to be able to convert between different schemas/text (JSON, XML, etc.), it would be good to describe the object models from the ground up in the specification.  Meaning, users would understand it a little more describing the traits > primitives > meanings > models.  Then there could be further details/sections that explain how the components fit in with each type of schema/text format.

**Comment by Venkata1920** [comment]
The CDM object model SDK is built to be backwards compatible from version 1.0 onwards. This includes the schema documents (versioned 1.0 onwards) too.
